name: Build package

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        shell: bash
        run: |
          python -m build --sdist --wheel

      - name: Install tarball
        shell: bash
        run: |
          pip install dist/*.gz

      - name: Test installation
        shell: bash
        run: |
          isofit
